# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xuci.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import B
import result

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("实词选择")
        Dialog.resize(496, 333)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(300, 50, 121, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(60, 40, 91, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(60, 70, 91, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(60, 100, 91, 19))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(60, 130, 91, 19))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(60, 160, 91, 19))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_6.setGeometry(QtCore.QRect(60, 190, 91, 19))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_7.setGeometry(QtCore.QRect(60, 220, 91, 19))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_8.setGeometry(QtCore.QRect(60, 250, 91, 19))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_9.setGeometry(QtCore.QRect(60, 280, 91, 19))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_10.setGeometry(QtCore.QRect(140, 40, 91, 19))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_11.setGeometry(QtCore.QRect(140, 70, 91, 19))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_12.setGeometry(QtCore.QRect(140, 100, 91, 19))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_13.setGeometry(QtCore.QRect(140, 130, 91, 19))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_14.setGeometry(QtCore.QRect(140, 160, 91, 19))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_15.setGeometry(QtCore.QRect(140, 190, 91, 19))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_16.setGeometry(QtCore.QRect(140, 220, 91, 19))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_17.setGeometry(QtCore.QRect(140, 250, 91, 19))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_18.setGeometry(QtCore.QRect(140, 280, 91, 19))
        self.checkBox_18.setObjectName("checkBox_18")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 110, 261, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("qunxiang.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        #self.pushButton.clicked.connect(self.xucires)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "虚词选择"))
        self.pushButton.setText(_translate("Dialog", "提交"))
        self.checkBox.setText(_translate("Dialog", "而"))
        self.checkBox_2.setText(_translate("Dialog", "何"))
        self.checkBox_3.setText(_translate("Dialog", "乎"))
        self.checkBox_4.setText(_translate("Dialog", "乃"))
        self.checkBox_5.setText(_translate("Dialog", "其"))
        self.checkBox_6.setText(_translate("Dialog", "且"))
        self.checkBox_7.setText(_translate("Dialog", "若"))
        self.checkBox_8.setText(_translate("Dialog", "所"))
        self.checkBox_9.setText(_translate("Dialog", "为"))
        self.checkBox_10.setText(_translate("Dialog", "焉"))
        self.checkBox_11.setText(_translate("Dialog", "也"))
        self.checkBox_12.setText(_translate("Dialog", "以"))
        self.checkBox_13.setText(_translate("Dialog", "因"))
        self.checkBox_14.setText(_translate("Dialog", "于"))
        self.checkBox_15.setText(_translate("Dialog", "与"))
        self.checkBox_16.setText(_translate("Dialog", "则"))
        self.checkBox_17.setText(_translate("Dialog", "者"))
        self.checkBox_18.setText(_translate("Dialog", "之"))

    def xucires(self):
        words=[]
        if self.checkBox.isChecked() == True:
            words.append(self.checkBox.text())
        if self.checkBox_2.isChecked() == True:
            words.append(self.checkBox_2.text())
        if self.checkBox_3.isChecked() == True:
            words.append(self.checkBox_3.text())
        if self.checkBox_4.isChecked() == True:
            words.append(self.checkBox_4.text())
        if self.checkBox_5.isChecked() == True:
            words.append(self.checkBox_5.text())
        if self.checkBox_6.isChecked() == True:
            words.append(self.checkBox_6.text())
        if self.checkBox_7.isChecked() == True:
            words.append(self.checkBox_7.text())
        if self.checkBox_8.isChecked() == True:
            words.append(self.checkBox_8.text())
        if self.checkBox_9.isChecked() == True:
            words.append(self.checkBox_9.text())
        if self.checkBox_10.isChecked() == True:
            words.append(self.checkBox_10.text())
        if self.checkBox_11.isChecked() == True:
            words.append(self.checkBox_11.text())
        if self.checkBox_12.isChecked() == True:
            words.append(self.checkBox_12.text())
        if self.checkBox_13.isChecked() == True:
            words.append(self.checkBox_13.text())
        if self.checkBox_14.isChecked() == True:
            words.append(self.checkBox_14.text())
        if self.checkBox_15.isChecked() == True:
            words.append(self.checkBox_15.text())
        if self.checkBox_16.isChecked() == True:
            words.append(self.checkBox_16.text())
        if self.checkBox_17.isChecked() == True:
            words.append(self.checkBox_17.text())
        if self.checkBox_18.isChecked() == True:
            words.append(self.checkBox_18.text())
        QtWidgets.QMessageBox.information(self.pushButton,"虚词频率",B.GetHistogram(words))